# Generated by Django 3.0.1 on 2020-01-18 15:08

import api.models.Usuario
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('cumpleanos', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Persona')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('colonia', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=50, null=True)),
                ('alergia', models.TextField(blank=True, max_length=100, null=True)),
                ('tipo_de_sangre', models.CharField(blank=True, choices=[('O-', 'O negativo'), ('O+', 'O positivo'), ('A-', 'A negativo'), ('A+', 'A positivo'), ('B-', 'B negativo'), ('B+', 'B positivo'), ('AB-', 'AB negativo'), ('AB+', 'AB positivo')], max_length=3, null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('tipo_de_cuenta', models.CharField(choices=[('I', 'Individual'), ('G', 'Grupal')], default='I', max_length=16)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.persona', models.Model),
            managers=[
                ('objects', api.models.Usuario.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='SubDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('disciplina_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdisciplinas', to='api.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dirgido', models.TextField(max_length=30)),
                ('estructura', models.TextField(max_length=30)),
                ('modalidad_semanal', models.TextField(max_length=30)),
                ('edad_minima', models.PositiveSmallIntegerField()),
                ('edad_maxima', models.PositiveSmallIntegerField()),
                ('precio', models.PositiveSmallIntegerField()),
                ('disciplinas', models.ManyToManyField(to='api.SubDisciplina')),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Nivel')),
                ('tipo_programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TipoPrograma')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='personas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
