# Generated by Django 3.0.1 on 2019-12-21 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('disciplina_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdisciplinas', to='api.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dirgido', models.CharField(max_length=30)),
                ('estructura', models.CharField(max_length=30)),
                ('modalidad_semanal', models.CharField(max_length=30)),
                ('edad_minima', models.PositiveSmallIntegerField()),
                ('edad_maxima', models.PositiveSmallIntegerField()),
                ('precio', models.PositiveSmallIntegerField()),
                ('disciplinas', models.ManyToManyField(to='api.SubDisciplina')),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Nivel')),
                ('tipo_programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TipoPrograma')),
            ],
        ),
    ]
