# Generated by Django 3.0.1 on 2019-12-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_disciplina_nivel_programa_subdisciplina_tipoprograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='dirgido',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='programa',
            name='estructura',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='programa',
            name='modalidad_semanal',
            field=models.TextField(max_length=30),
        ),
    ]
