# Generated by Django 3.0.1 on 2020-01-18 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200118_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='personas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas_usuario', to='api.Persona'),
        ),
    ]
