# Generated by Django 3.0.1 on 2019-12-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191219_0500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidoMaterno',
            new_name='apellido_materno',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidoPaterno',
            new_name='apellido_paterno',
        ),
    ]
