# Generated by Django 3.0.1 on 2019-12-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191219_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_de_sangre',
            field=models.CharField(blank=True, choices=[('O-', 'O negativo'), ('O+', 'O positivo'), ('A-', 'A negativo'), ('A+', 'A positivo'), ('B-', 'B negativo'), ('B+', 'B positivo'), ('AB-', 'AB negativo'), ('AB+', 'AB positivo')], max_length=3, null=True),
        ),
    ]
