# Generated by Django 3.0.1 on 2019-12-20 01:03

import api.models.Usuario
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191219_1915'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', api.models.Usuario.UsuarioManager()),
            ],
        ),
    ]
