# Generated by Django 3.0.1 on 2020-01-21 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Grupo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_persona',
            field=models.CharField(blank=True, choices=[('A', 'Alumno'), ('P', 'Profesor')], default='A', max_length=2, null=True),
        ),
    ]
