# Generated by Django 3.0.1 on 2020-01-21 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200121_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='nivel',
        ),
        migrations.AddField(
            model_name='nivel',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Programa'),
        ),
    ]
