# Generated by Django 3.0.1 on 2020-01-21 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200121_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='nivel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Nivel'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='parcialidades',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Una exhibición'), (3, 'Tres pagos')]),
        ),
        migrations.AlterField(
            model_name='programa',
            name='disciplinas',
            field=models.ManyToManyField(to='api.Disciplina'),
        ),
    ]
