# Generated by Django 3.0.1 on 2020-01-23 20:28

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200121_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupo',
            name='cupo',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='archivo',
            field=models.FileField(upload_to='comprobantes', validators=[api.validators.validate_comprobante]),
        ),
    ]
