# Generated by Django 3.0.1 on 2020-01-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200123_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobante',
            old_name='aprovado',
            new_name='aprobado',
        ),
    ]
