# Generated by Django 3.0.1 on 2020-01-23 22:28

import api.utils
import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200123_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobante',
            old_name='comprobante',
            new_name='inscripcion',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='parcialidad',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='archivo',
            field=models.FileField(upload_to=api.utils.hashImage, validators=[api.validators.validate_comprobante]),
        ),
    ]
