# Generated by Django 3.0.1 on 2020-01-24 20:27

import api.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_comprobante_tipo_de_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='dias',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='final',
            field=api.models.fields.DayOfTheWeekField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('7', 'Domingo')], max_length=13),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nivel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='api.Nivel'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveles', to='api.Programa'),
        ),
    ]
