# Generated by Django 3.0.1 on 2020-01-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200124_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='api.Nivel'),
        ),
    ]
