# Generated by Django 3.0.1 on 2020-01-24 20:33

import api.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200124_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='dias',
            field=api.models.fields.DayOfTheWeekField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('7', 'Domingo')], default='1', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupo',
            name='final',
            field=models.TimeField(),
        ),
    ]
