# Generated by Django 3.0.4 on 2020-03-12 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200312_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='bloques',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='dirigido',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='edad_maxima',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='edad_minima',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='estructura',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='modalidad_semanal',
        ),
        migrations.AddField(
            model_name='bloque',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques', to='api.Nivel'),
        ),
        migrations.AddField(
            model_name='bloque',
            name='precio',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivel',
            name='dirigido',
            field=models.TextField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivel',
            name='edad_maxima',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivel',
            name='edad_minima',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivel',
            name='estructura',
            field=models.TextField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivel',
            name='modalidad_semanal',
            field=models.TextField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
