# Generated by Django 3.0.4 on 2020-03-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200312_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='tipo_programa',
        ),
        migrations.DeleteModel(
            name='TipoPrograma',
        ),
    ]
