# Generated by Django 3.0.4 on 2020-03-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200328_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='bloque',
        ),
        migrations.AddField(
            model_name='nivel',
            name='precio_semana_dos',
            field=models.PositiveSmallIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivel',
            name='precio_semana_uno',
            field=models.PositiveSmallIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bloque',
        ),
    ]
